name: ldes_fragment_maker_and_publisher

on:
  pull_request:
    types: [closed]

jobs:
  ldes_fragment_maker_and_publisher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: check if pull request merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
              echo "Pull request merged"
          else
              echo "Pull request not merged"
              exit 1
          fi
      - name: get the current hash of the main branch and the changed files
        run: |
          current_hash=$(git rev-parse main)
          last_hash=$(cat .github/last_ldes_hash)
          echo "Current hash: $current_hash"
          echo "Last hash: $last_hash"
          changed_files=$(git diff --name-only $last_hash $current_hash)
          echo "Changed files: $changed_files"

      - name: LDES fragment maker and publisher
        uses: cedricdcc/ldes-fragment-maker-action@latest
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ldes
      - name: Commit change of hash file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com
          git add .github/last_ldes_hash
          git commit -m "Update LDES hash file"
          git push
